### ISSUE TITLE
[Feature request] add delayed display of dialog

### ISSUE THREAD

**Issue by bubbleguuum** [tashilapathum/PleaseWait#1]
Would be great if you could configure a delay for showing the dialog.
Maybe taking inspiration from https://github.com/tasomaniac/DelayedProgress
This is useful when you have a task that could take very little time, for not spawning a dialog in that case.

**Comment by tashilapathum** [comment]
Thanks for the feedback!
I'll add it in the next update.

**Comment by tashilapathum** [comment]
This was added in the v0.4.0. The method names and the implementation are different but it should be possible to achieve the same behavior.
