### ISSUE TITLE
class PleaseWaitDialog is final, cannot override onDismiss(), onCancel(), ....

### ISSUE THREAD

**Issue by bubbleguuum** [tashilapathum/PleaseWait#4]
Unlike Java, Kotlin make classes `final` by default, thus they cannot be extended.
Thus it is not possible to subclass class `PleaseWaitDialog` to override `onDismiss(), `onCancel()` and possibly other functions:

Example in Java, this does not compile (probably with Kotlin too) because PleaseWaitDialog is `final`

```
 PleaseWaitDialog dialog = new PleaseWaitDialog(this) {
                    public void onCancel(DialogInterface d) {
                           // do something
                    }
                };
```

I'm not super familiar with Kotlin, but the solution I think is to declare PleaseWaitDialog open:

```
open class PleaseWaitDialog {
...
```

**Comment by tashilapathum** [comment]
I'll include this in the next release

**Comment by bubbleguuum** [comment]
Thank you for your response.

I tested a modified version (converted to Java) to be able to override `onCancel()` using an anonymous class (example in first post).
However it does not work because `DialogFragment#show(FragmentManager manager, String tag)` fails with:

java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.

It doesn't like an anonymous `PleaseWaitDialog` instance.

A solution to this issue would be to add this function to set a cancel listener (and not declare the class `open` as it cannot not work):
```
 public void setOnCancelListener(DialogInterface.OnCancelListener listener) {
      onCancelListener = listener;
   }
```

And add this override to `onCancel()` in `PleaseWaitDialog` :

```
 @Override
   public void onCancel(@NonNull DialogInterface dialog) {
      super.onCancel(dialog);
      if(onCancelListener != null) {
         onCancelListener.onCancel(dialog);
      }
   }
```

Same thing could be done for the dismiss listener.

**Comment by tashilapathum** [comment]
Thanks for your suggestion. I'll definitely test it out because I don't have an idea either.

**Comment by tashilapathum** [comment]
I looked this up and found that it's not recommended to use inner classes for Fragments as it may cause a memory leak. I'll add some listeners later but for now I've made PleaseWaitDialog class open so you can subclass it for your purpose.
